### PR TITLE
Adding Enum.GetNames method

### PR DESCRIPTION
**Pull request by denhnure**

### CODE REVIEW

**Comment by fred-perkins** [comment]
All tests pass bar one; BasicTests -> TestMetadata. This is a known issue which is a pain to sort out. Basically the compiler generates a special file with all the relevant metadata and its assignment members and methods. If you apply the linked patch to your branch it should fix the problem; [Basic/Metadata/Baseline.txt patch](https://gist.github.com/fred-perkins/621dd30b6eaa6f9828da81635feac894)

**Comment by denhnure** [comment]
Thank you, Fred. I fixed failing unit test :)

image

**Comment by fred-perkins** [comment]
PR needs to be updated to work against DSharp-SDK

**Comment by fred-perkins** [comment]
Closing PR as with the main branch being migrated, we want to look at re implementing this elsewhere

**Pull request closed without merging**
