### PR TITLE
Fix99 - Fixing List<T>(IEnumerable<T>)

### PR DESCRIPTION
**Pull request by adrianodfo**
Fixing the constructor call of the List<T> class that contains elements copied from the specified collection (array).

### CODE REVIEW

**Comment by adrianodfo** [comment]
Now the 3 constructors for a List collection shall work on javascript.

**Comment by fred-perkins** [comment]
PR needs to be updated to work against DSharp-SDK - If still required.

**Comment by adrianodfo** [comment]
Updated to work against DSharp-SDK

**Comment by isc30** [comment]
Seems like this PR doesn't add anything except for some tests, can you explain the reasoning behind this? @adrianodfo

**Comment by fred-perkins** [comment]
@isc30  If you look at the commit history you'll see it's missing some of the work he did. Looks like when we moved the branch over to point at the new feature branch it's got lost in translation

**Pull request closed without merging**
