### PR TITLE
fixing List<T>.Contains to make it CLR compatible.

### PR DESCRIPTION
**Pull request by novagelida**

### CODE REVIEW

**Comment by novagelida** [comment]
there you go: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs

**Comment by novagelida** [comment]
I updated the branch and run the tests. All tests are passing:

image

Despite the fix on Contains method, the compiler will still accept generic object to be pass as parameters. This is happening as the List class is directly mapped to its javascript counterpart. Furthermore, given the absence of support for generic, any sort of type check on Contains parameter will be performed. The same is already happening for the Add method. Despite the type of the list, the Add method will accept any object.

**For our goal this is acceptable as we just need to make the List class compliant to CLR.**

**Comment by isc30** [comment]
agreed. good job 👍

**Comment by isc30** [comment]
Not sure if this PR is up to date after all the changes in the interfaces branch

**Pull request closed without merging**
